language: cpp
os: linux
dist: trusty
compiler: gcc

before_script:
  - git clone --branch=5.10 git://code.qt.io/qt/qt5.git
  - pushd qt5
  - perl init-repository --module-subset=qtbase,qtimageformats
  - ./configure -opensource -nomake examples -nomake tests -confirm-license
  - make -j2
  - sudo make install
  - popd

script:
  - mkdir -p build
  - pushd build
  - ../qt5/qtbase/bin/qmake .. -config release
  - make -j2
  - popd