language: cpp
os:
  - linux
dist: trusty
compiler:
  - gcc

cache:
  directories:
    - qt5

before_script:
  - if [ ! -d qt5 ] ; then source make_qt.sh ; fi

script:
  - which qmake
  - which lrelease
  - mkdir -p build
  - pushd build
  - qmake .. -config release
  - make -j2
  - popd