language: cpp
os:
  - linux
dist: trusty
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt update -qq

install:
  - sudo apt install -qq -y qt5-default qt5-qmake qttools5-dev qttools5-dev-tools

before_script:
  - mkdir -p build
  - pushd build
  - qmake .. -config release
  - popd

script:
  - make -C build