language: cpp
os: linux
sudo: false
dist: trusty
compiler: gcc

cache:
  directories:
    - qt5

before_script:
  - mkdir -p qt5
  - if [ ! -d qt5/.git ] ; then rm qt5 -Rf ; git clone --branch=5.10 git://code.qt.io/qt/qt5.git ; fi
  - pushd qt5
  - if [ ! -d qtbase/.git ] ; then perl init-repository --module-subset=qtbase,qtimageformats,qtmultimedia,qttools ; fi
  - if [ ! -f config.summary ] ; then ./configure -prefix `pwd`/build -opensource -confirm-license -nomake examples -nomake tests ; fi
  - if [ ! -d build ] ; then make -j2 > /dev/null && make install ; fi
  - popd

script:
  - mkdir -p build
  - pushd build
  - ../qt5/build/bin/qmake .. -config release
  - make -j2
  - popd