language: cpp
os:
  - linux
dist: trusty
compiler:
  - gcc

before_install:

install:

before_script:
  - if [ ! -d qt5 ]
  - then
  - git clone --branch=5.10 git://code.qt.io/qt/qt5.git
  - pushd qt5
  - perl init-repository --module-subset=qtbase,qtimageformats
  - ./configure -static -opensource -nomake examples -nomake tests -confirm-license
  - make -j2
  - sudo make install
  - popd
  - fi

script:
  - which qmake
  - which lrelease
  - mkdir -p build
  - pushd build
  - qmake .. -config release
  - make -j2
  - popd